[versions]
ktlint = "0.50.0"
paperweight = "2.0.0-beta.19"
pluginyml = "0.8.0"

# Platforms
minecraft = "1.21.11-R0.1-SNAPSHOT"

# Libraries
cloud = "1.8.4"
guice = "5.1.0"
configurate = "4.1.2"

# Minecraft Plugins
placeholderapi = "2.11.7"

[libraries]

# Platform
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "minecraft" }

# Libraries
cloudPaper = { group = "cloud.commandframework", name = "cloud-paper", version.ref = "cloud" }
guice = { group = "com.google.inject", name = "guice", version.ref = "guice" }
assistedInject = { group = "com.google.inject.extensions", name = "guice-assistedinject", version.ref = "guice" }
configurateHocon = { group = "org.spongepowered", name = "configurate-hocon", version.ref = "configurate"}

# Minecraft Plugins
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderapi" }

[plugins]
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
pluginyml = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginyml" }
